python-adaptive/adaptive

- README.rst
- RELEASE.md
- adaptive/learner/learner2D.py
- adaptive/tests/test_cquad.py
- adaptive/tests/test_learner1d.py
- adaptive/tests/test_learners.py
- adaptive/tests/test_runner.py
- benchmarks/asv.conf.json
- docs/source/tutorial/tutorial.rst
- learner.ipynb
I've changed all mentions of GitLab to GitHub.
We used [this](https://github.com/python-adaptive/adaptive/issues/5#issuecomment-448708930) script to transfer all open and closed issues to GitHub and all open PRs from GitLab to GitHub.
> change urls from GitLab to GitHub

- adaptive/learner/learner1D.py
- adaptive/tests/test_learner1d.py
This reverts the behavior that we've decided upon a long time ago.
The bug was introduced a few months ago.
> handle NaN losses and add a test, closes #145

- adaptive/tests/test_runner.py
- azure-pipelines.yml
- test-requirements.txt
The Conda Environment task is deprecated
https://github.com/Microsoft/azure-pipelines-tasks/pull/9573
Example uses are [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04).
> invoke conda directly in CI

- adaptive/learner/balancing_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learnerND.py
- adaptive/learner/triangulation.py
Because of the following DeprecationWarning:
```
DeprecationWarning: Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
> import Iterable and Sized from collections.abc

- adaptive/learner/balancing_learner.py
- adaptive/tests/test_balancing_learner.py
This fixes #159.
@akhmerov could you take a look at this?
> Distribute first points in a BalancingLearner

- adaptive/learner/learnerND.py
- adaptive/tests/test_learnernd.py
The test that I added fails (or not really fails but continues forever).
I stumbled upon this when trying to fix the the following `Warnings` : 
```python
adaptive/tests/test_learnernd.py::test_faiure_case_LearnerND
adaptive/tests/test_learnernd.py::test_interior_vs_bbox_gives_same_result
/Users/basnijholt/Work/adaptive/adaptive/learner/learnerND.py:529: RuntimeWarning: divide by zero encountered in double_scalars
scale_multiplier = 1 / self._scale
adaptive/tests/test_learnernd.py::test_faiure_case_LearnerND
adaptive/tests/test_learnernd.py::test_interior_vs_bbox_gives_same_result
/Users/basnijholt/Work/adaptive/adaptive/learner/learnerND.py:548: RuntimeWarning: invalid value encountered in double_scalars
scale_factor = np.max(np.nan_to_num(self._scale / self._old_scale)) …
```
> test flat bands in the LearnerND

- docs/source/_static/js/theme.js
- docs/source/conf.py
This is not a proper fix but before I discovered how to fix it correctly this might do.
After this plot.ly and HoloMaps will correctly show.
> Temporarily fix docs

- adaptive/runner.py
See https://github.com/python-adaptive/adaptive/issues/156
This prevent the 'OSError: handle is closed' after the runner
is closed in Python 3.7
> do not force shutdown the executor in the cleanup

- adaptive/notebook_integration.py
- docs/source/docs.rst
- docs/source/tutorial/tutorial.AverageLearner.rst
- docs/source/tutorial/tutorial.BalancingLearner.rst
- docs/source/tutorial/tutorial.DataSaver.rst
- docs/source/tutorial/tutorial.IntegratorLearner.rst
- docs/source/tutorial/tutorial.Learner1D.rst
- docs/source/tutorial/tutorial.Learner2D.rst
- docs/source/tutorial/tutorial.LearnerND.rst
- docs/source/tutorial/tutorial.SKOptLearner.rst
- docs/source/tutorial/tutorial.advanced-topics.rst
- docs/source/tutorial/tutorial.custom_loss.rst
This reduces the size of the `html` folder of 93.3 MB (master) to 60.1 MB (this branch).
Related: https://github.com/pyviz/holoviews/pull/3581
> do not inline the HoloViews JS

- docs/environment.yml
~~~Related https://github.com/jupyter-widgets/jupyter-sphinx/pull/27 and https://github.com/jupyter-widgets/jupyter-sphinx/issues/26.~~~
edit:
In the readthedocs.org settings we enabled to install the repo code.
> use the repo code in docs execute

- setup.py
As by the suggestion of @Carreau in #179.
> use setup(..., python_requires='>=3.6'), closes #179

- adaptive/learner/learner2D.py
@andrenmelo, this is the (a) solution.
@python-adaptive/core what do you think?
> 2D: do not return points outside the bounds, closes #181

- azure-pipelines.yml
It's been a while since `pytest` command exists (pytest 3.0.0 released in August 2016). From [this](https://docs.pytest.org/en/latest/changelog.html#id760):
> Introduce pytest command as recommended entry point. Note that py.test still works and is not scheduled for removal.
> use pytest rather than py.test

- adaptive/utils.py
- docs/environment.yml
- environment.yml
- setup.py
Right now, if a program crashes in the middle of saving, you lose all your data. This ensures that the old file is first moved, then the new file is saved, and only then the old file is removed.
This is not a hypothetical scenario but happens **every day** for some people that I work with ATM.
> ensure atomic writes when saving a file

- adaptive/learner/balancing_learner.py
- adaptive/tests/test_balancing_learner.py
This is useful for example for the `AverageLearner1D` and `2D` where sampling on `npoints` won't sample all learners equally, because that's not how `npoints` is defined there.
> BalancingLearner: add a "cycle" strategy, sampling the learners one by one

- adaptive/__init__.py
- adaptive/learner/__init__.py
- adaptive/learner/sequence_learner.py
- adaptive/tests/test_learners.py
- docs/source/reference/adaptive.learner.sequence_learner.rst
- docs/source/reference/adaptive.rst
- docs/source/tutorial/tutorial.SequenceLearner.rst
- docs/source/tutorial/tutorial.rst
Adaptive has really great features to trivially parallelize and auto-save your simulation, however, sometimes you just can't formulate your problem in one of the `Learner`s. Then just for this single problem, one needs to write a lot of code to basically do what Adaptive can already do for you.
Therefore I've implemented a `SequenceLearner` that doesn't do a whole lot of fancy things, except for being a `BaseLearner` child.
With this one can easily run, `save` (and periodically save), `load`, `live_info`, and `live_plot` one's progress (if one implements a simple `plotter` function).
It's great when running simulations that might crash because if one uses periodic saving, the learner just picks up where it was before it crashed (in contrary to `ipyparallel.Client().map` where one needs to …
> Add a SequenceLearner

- docs/environment.yml
- docs/source/conf.py
- docs/source/tutorial/tutorial.AverageLearner.rst
- docs/source/tutorial/tutorial.BalancingLearner.rst
- docs/source/tutorial/tutorial.DataSaver.rst
- docs/source/tutorial/tutorial.IntegratorLearner.rst
- docs/source/tutorial/tutorial.Learner1D.rst
- docs/source/tutorial/tutorial.Learner2D.rst
- docs/source/tutorial/tutorial.LearnerND.rst
- docs/source/tutorial/tutorial.SKOptLearner.rst
- docs/source/tutorial/tutorial.SequenceLearner.rst
- docs/source/tutorial/tutorial.advanced-topics.rst
- docs/source/tutorial/tutorial.custom_loss.rst
This again needs https://github.com/python-adaptive/adaptive/pull/169. However, I have manually executed those commands from the CI.
See https://adaptive.readthedocs.io/en/test_documentation/ when the build finished.
> use jupyter_sphinx v0.2.0 from conda instead of my branch

- adaptive/learner/learnerND.py
Currently, the `LearnerND` cannot access the unscaled value in the `loss_per_simplex`.
This PR fixes this by passing the scale. This fixes a regression introduced when we added scaling.
Now the following code:
```python
import numpy as np
adaptive.notebook_extension()
def isoline_loss_function(y_iso, sigma, priority=1):
from adaptive.learner.learnerND import default_loss
def gaussian(x, mu, sigma):
return np.exp(-(x - mu) ** 2 / sigma ** 2)
def loss(simplex, values, value_scale):
distance = np.mean([abs(y_iso * value_scale - y) for y in values])
return priority * gaussian(distance, 0, sigma) + default_loss(simplex, values, value_scale)
return loss
level = 0.5
loss = isoline_loss_function(y_iso=level, sigma=1, priority=0.3)
def f(xy):
x, y = xy
return x ** 2 + y ** 2 / 2 + …
```
> pass value_scale to the LearnerND's loss_per_simplex function

- adaptive/learner/learner2D.py
For symmetry reasons, I add `triangle_loss` which works with the `Learner2D`.
Currently, it is very slow, for a learner with 1000 points:
```python
ip = learner.ip()
%timeit adaptive.learner.learner2D.triangle_loss(ip)
%timeit adaptive.learner.learner2D.default_loss(ip)
```
```
652 ms ± 154 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.92 ms ± 96.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Result:
> 2D: add triangle_loss

- adaptive/learner/learner1D.py
I've needed this many times and the discussion in the chat now also made it clear that this is needed.
Now you won't have to look at plots like this:
> add scatter_or_line argument to Learner1D.plot

- adaptive/runner.py
Closes #206.
It is not obvious that this blocks the kernel, but it does hang forever and does not error.
```python
adaptive.notebook_extension()
f = lambda xy: xy[0]**2 + xy[1]**2
learner = adaptive.Learner2D(f, bounds=[(-1, 1), (-1, 1)])
runner = adaptive.Runner(learner, goal=lambda l: l.npoints >= 1000)
```
This PR makes sure an error is raised, however, might this be caused by an underlying issue?
> WIP: raise an error when using a lambda and default executor

- adaptive/learner/skopt_learner.py
- adaptive/tests/test_skopt_learner.py
This fixes issue #233 
Tests checked. Per-commit checked.
Implemented additional test for this case.
Changed `data` type to `OrderedDict` to comply with other learners.
> Fix SKOptLearner for multi variate domain (issue #233)

- README.rst
I frequently get this question, so I think it will be good to add it to the website.
This will probably be good until we have published [the paper](https://gitlab.kwant-project.org/qt/adaptive-paper).
I've made Adaptive italic because this is what is recommended (in a writing course that I took) for names of software packages.
The DOI I chose will always point to the latest release on Zenodo.
@akhmerov and @jbweston, what do you think?
> add a section of "How to cite" Adaptive

- .github/pull_request_template.md
Now it should be more clear that one should run `pre-commit`.
People probably don't read https://adaptive.readthedocs.io/en/latest/docs.html#development before contributing.
@jbweston and @akhmerov, what do you think?
> add a Pull Request template

- .flake8
- .isort.cfg
- .pre-commit-config.yaml
- README.rst
- adaptive/runner.py
- adaptive/tests/test_learners.py
- adaptive/tests/test_notebook_integration.py
- adaptive/tests/test_runner.py
- adaptive/tests/test_skopt_learner.py
- azure-pipelines.yml
- pyproject.toml
- pytest.ini
- setup.py
- test-requirements.txt
- tox.ini
Adds tox.
* Use `tox.ini` for all configuration
* Test against Python 3.6, 3.7, and 3.8
* Tests on Windows, macOS, and Ubuntu
* Run tests with the bare dependencies (so only the bare requirements)
* Upload Coverage reports to [codecov.io](https://codecov.io/gh/python-adaptive/adaptive)
* Define dependencies all in `setup.py`
* Removes double occurrence of the pipelines
* Adds `flaky` to tests that sometimes fail
* Several small fixes in the tests
* Use `ProcessPoolExecutor` by default for Windows because it seems to work
Notes
* Reusing the Python env in different jobs [isn't possible](https://stackoverflow.com/questions/58322287/reuse-workspace-from-other-job-in-azure-pipelines) :( 
* ~~black fails because of https://github.com/psf/black/issues/1207~~ this is fixed
> use tox, closes #238

- adaptive/notebook_integration.py
Based on the default style of the Jupyterlab table.
In Jupyterlab:
In the notebook:
Fixes #250
> improve the style of the live_info widget, closes #250

- adaptive/notebook_integration.py
The color of the reported overhead will change to red if it's bad and to green if it's good.
> color the overhead between red and green

- adaptive/tests/test_runner.py
It seems to fail a lot on Windows, making the whole pipeline fail.
> disable test of runner using distributed

- .gitignore
Add .vscode to gitignore to avoid tracking editor config.
> MNT: add vscode config directory to .gitignore

- README.rst
This adds instructions for using Jupyterlab with Adaptive.
> add instructions for installing labextensions for Jupyterlab

- azure-pipelines.yml
- docs/source/tutorial/tutorial.parallelism.rst
Currently, the example is incorrect.
> use __name__ == "__main__" for the MPIPoolExecutor

- docs/environment.yml
HoloViews didn't have a strict pinning for it.
In the new version https://github.com/holoviz/pyviz_comms/blob/v0.7.2/pyviz_comms/__init__.py#L102
was removed, while holoviews=1.11.3 seems to depend on it.
> fix docs build and pin pyviz_comms=0.7.2

- adaptive/runner.py
- adaptive/tests/test_runner.py
- docs/source/conf.py
- docs/source/tutorial/tutorial.parallelism.rst
- environment.yml
- setup.py
This adds support for `loky` which has a `ProcessPoolExecutor` that can for example use `cloudpickle`.
> add support for loky

- environment.yml
- setup.py
This means that we won't run into https://github.com/joblib/loky/issues/240
~~This can be merged when ipyparallel 6.2.5 is on conda-forge.~~
On conda-forge now: https://github.com/conda-forge/ipyparallel-feedstock/pull/48
Fixes #249.
> minimally require ipyparallel 6.2.5

- adaptive/learner/average_learner.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/data_saver.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/sequence_learner.py
- adaptive/tests/test_pickling.py
- setup.py
- tox.ini
I realized that in some cases it's very useful to pickle learners. For example to send it over the network when parallelizing code.
With these changes, most learners become picklable.
> make learners picklable

- adaptive/runner.py
- docs/source/tutorial/tutorial.advanced-topics.rst
Enable the `Runner` to with with unhashable points.
Fixes #267.
> make the Runner work with unhashable points

- adaptive/learner/average_learner.py
- adaptive/tests/test_average_learner.py
Adds `min_npoints` as a parameter to the `AverageLearner`.
Closes https://github.com/python-adaptive/adaptive/issues/273
> AverageLearner: implement min_npoints

- adaptive/tests/test_learners.py
All tests fail with
```bash
______________ ERROR collecting adaptive/tests/test_learnernd.py ______________
ImportError while importing test module 'D:\a\1\s\adaptive\tests\test_learnernd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox\py36-alldeps\lib\site-packages\_pytest\python.py:511: in _importtestmodule
mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox\py36-alldeps\lib\site-packages\py\_path\local.py:701: in pyimport
__import__(modname)
.tox\py36-alldeps\lib\site-packages\_pytest\assertion\rewrite.py:152: in exec_module
exec(co, module.__dict__)
adaptive\tests\test_learnernd.py:7: in <module>
from .test_learners import generate_random_parametrization, ring_of_fire
.tox\py36-alldeps\lib\site-packages\_pytest\assertion\rewrite.py:152: …
```
> prevent ImportError due to scikit-optimize and sklearn incompatibility

- setup.py
Builds are failing.
See https://github.com/scikit-optimize/scikit-optimize/issues/931
> temporarily pin scikit-learn<=0.23.1

- adaptive/_version.py
Fixes warning printed:
```
/gscratch/home/a-banijh/miniconda3/envs/py38/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
warnings.warn(
```
> update to miniver 0.7.0

- .pre-commit-config.yaml
- adaptive/tests/test_cquad.py
- adaptive/tests/test_learners.py
- adaptive/tests/test_pickling.py
- adaptive/tests/test_skopt_learner.py
- tox.ini
Also adds blacken-docs.
I've added support for Jupyter Sphinx here https://github.com/asottile/blacken-docs/pull/37.
Blacken-docs is failing, this PR will fix that: https://github.com/asottile/blacken-docs/pull/57
> bump pre-commit filter dependencies and add blacken-docs

- adaptive/learner/average_learner.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/sequence_learner.py
- setup.py
- tox.ini
This was a suggestion of @jbweston some time ago.
Using this, the learners are picklable regardless of the serialization package chosen.
This also means that we can e.g. use lambda functions when using a `ProcessPoolExecutor` and do not need `loky` per se.
I am making these changes now because I am finding that in some cases it's not preferable to use `cloudpickle` to serialize simple dictionaries (see https://github.com/cloudpipe/cloudpickle/issues/375).
> always serialize the function using cloudpickle

- adaptive/runner.py
- adaptive/tests/test_runner.py
- docs/environment.yml
- setup.py
Make loky a default on Windows and MacOS but not on Linux.
I am doing this because several people have indicated that they are experiencing issues with Loky on a Linux cluster.
On Windows and MacOS loky is preferred because `ProcessPoolExecutor` won't work in interactive environments.
Closes https://github.com/python-adaptive/adaptive/issues/301
See also
- https://github.com/python-adaptive/adaptive/issues/292
- https://github.com/python-adaptive/adaptive/issues/299
> make loky a default on Windows and MacOS but not on Linux

- .github/workflows/pythonpublish.yml
Adds a Github Action script that automatically publishes to PyPI when a tag is added. This works very well with miniver.
I've been using this in https://github.com/basnijholt/adaptive-scheduler and https://github.com/basnijholt/aiokef for some time and it works very well.
> add pythonpublish.yml

- docs/source/tutorial/tutorial.rst
> remove the requirements from the tutorial landing page

- adaptive/learner/learner1D.py
- docs/source/tutorial/tutorial.custom_loss.rst
add resolution_loss_function for Learner1D like we have for the Learner2D.
> add resolution_loss_function for Learner1D

- .github/workflows/tox.yml
- .pre-commit-config.yaml
- README.rst
- benchmarks/asv.conf.json
- environment.yml
- setup.py
Let's stick with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) and drop Python 3.6 support.
> bump to Python≥3.7

- adaptive/learner/integrator_coeffs.py
- adaptive/learner/integrator_learner.py
- adaptive/tests/test_cquad.py
- adaptive/utils.py
Currently, the having the following in a script:
```
import gpytorch
```
breaks any Python process because of https://github.com/pytorch/pytorch/issues/54063.
This is not a proper fix but avoiding the problem. 
Howver, rather than doing any math on import, I think it is a better style to only evaluate the coefficients when required.
> lazily evaluate the integrator coefficients

- adaptive/learner/integrator_coeffs.py
We should raise an `AttributeError` as is appropriate when an attribute isn't found.
Fixes #314
@akhmerov, if you would give this your blessing?
@caenrigen, this should fix you issue.
> raise an AttributeError when attribute doesn't exists, closes #314

- adaptive/learner/average_learner.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
After having answered "How do I get the data" 1000 times and having written the code to convert `learner.data` to a numpy array many times as well, I decided to just add it in Adaptive.
I have implemented it such that a single array is returned with the points and values concatenated. An alternative is to return the points and values as separate arrays.
> add to_numpy methods

- adaptive/runner.py
call self._process_futures on canceled futures when BlockingRunner is done.
thanks @jgukelberger for noticing this
Fixes #319
> call self._process_futures on canceled futures when BlockingRunner is done

- adaptive/learner/average_learner.py
- adaptive/tests/test_average_learner.py
> AverageLearner: fix zero mean

- adaptive/learner/learner1D.py
A tiny correction to the doc string, as discussed in #322.
Fixes #322
^ this did not pass (but I haven't modified anything other than the doc string), here's what I get:
```pytb
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-append --cov-fail-under=70 --cov-report=
inifile: /Users/me/adaptive/tox.ini
rootdir: /Users/me/adaptive
```
> Update doc string for resolution_loss_function

- adaptive/learner/average_learner1D.py
- adaptive/learner/base_learner.py
- adaptive/learner/learner1D.py
- adaptive/tests/test_average_learner.py
- adaptive/tests/test_average_learner1d.py
- adaptive/tests/test_learners.py
- setup.py
- tox.ini
I am splitting up https://github.com/python-adaptive/adaptive/pull/244 into smaller parts.
Since it has been ready for review for almost 2 years but no-one has looked at it, I will go ahead and auto-complete this as soon as the `typeguard` and `mypy` issues have been solved.
> Learner1D type hints and add typeguard to pytest tests

- adaptive/learner/base_learner.py
- adaptive/learner/learnerND.py
- adaptive/tests/test_pickling.py
- adaptive/utils.py
This makes the LearnerND pickleable.
Other learners have been made pickleable in https://github.com/python-adaptive/adaptive/pull/264.
> Make LearnerND pickleable

- adaptive/learner/learnerND.py
- docs/source/docs.rst
> take out a cut from the 3D sphere, LearnerND example

- docs/environment.yml
- docs/source/_static/custom.css
- docs/source/conf.py
- docs/source/docs.rst
Use latest versions in docs creation.
> Documentation conda environment update to latest versions

- README.rst
- docs/Makefile
- docs/environment.yml
- docs/logo.py
- docs/logo_animated.py
- docs/source/conf.py
Adds a fancy moving logo at a minimal cost of 300 KB.
> Add an animated logo that shows the working of Adaptive

- adaptive/learner/learner1D.py
- adaptive/tests/test_learner1d.py
@bernardvanheck found an issue that occurs when using multiple cores on the following function
Here the middle region is exponentially flat and the blue curve is a homogeneous plot and the orange points are of the finished learner with a very small loss (<0.01).
I think that a learner should report an infinite loss whenever the bounds aren't included.
Having that, means that the issue I described above is much less likely to occur.
The following code snippet results in a learner with a small loss after only 3 points.
```
from adaptive.learner.learner1D import curvature_loss_function, Learner1D
from adaptive.runner import replay_log
learner_fail = Learner1D(
lambda x: x, bounds=(-400e-6, 400e-6), loss_per_interval=curvature_loss_function(),
)
runner_log = [
("ask", 4), …
```
> Learner1D: return inf loss when the bounds aren't done

- docs/logo_animated.py
- docs/source/conf.py
- docs/source/logo.rst
@akhmerov, it turned out that Github didn't properly hide the custom directive, so I had to `.. include::` a file with the `.. animated-logo::` directive.
So instead of having two levels of abstraction, now we only have one.
> use jupyter-sphinx instead of custom Sphinx directive

- environment.yml
- setup.py
pin scikit-learn to 0.24.2, because of https://github.com/scikit-optimize/scikit-optimize/issues/1059
> pin scikit-learn to 0.24.2, because of https://github.com/scikit-optimize/scikit-optimize/issues/1059

- adaptive/learner/learner1D.py
If a function evaluates over a point where it is not defined, NaN will be returned.
In the case of a function R -> R^n, it caused `_update_scale` to compute `self._scale[1] = nan`,
which in turns led to the evaluation of the function on all other points to be NaN, causing an
infinite loop, as reported in issue #339.
Using `np.nanmin` and `np.nanmax` in place of `np.min` and `np.max` seems to solve the issue.
Fixes  #339
> Fix NaN issue for Learner1D R -> R^n

- .pre-commit-config.yaml
- adaptive/learner/average_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/triangulation.py
- adaptive/notebook_integration.py
- adaptive/tests/algorithm_4.py
- adaptive/tests/test_learner1d.py
- adaptive/tests/test_learners.py
- adaptive/tests/test_pickling.py
- adaptive/tests/test_skopt_learner.py
- adaptive/tests/unit/test_learnernd.py
- adaptive/tests/unit/test_learnernd_integration.py
- benchmarks/benchmarks/benchmarks.py
- docs/logo.py
- docs/logo_animated.py
> Update pre-commit filters versions

- adaptive/tests/test_runner.py
> Skip ipyparallel test on MacOS

- .github/workflows/typeguard.yml
- adaptive/runner.py
- noxfile.py
> Run seperate typeguard job (because it is much slower)

- adaptive/learner/learner2D.py
Remove scipy deprecation in `learner2D.py`
```
DeprecationWarning: Delaunay attribute 'vertices' is deprecated in favour of 'simplices' and will be removed in Scipy 1.11.0.
```
> Remove scipy deprecation warnings

- docs/environment.yml
- docs/source/algorithms_and_examples.md
- docs/source/logo.md
Makes the contour around the animated logo transparent.
Currently it looks like:
> Add transparent logo in WebM format (for dark mode)

- adaptive/learner/average_learner.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/data_saver.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/sequence_learner.py
- adaptive/tests/test_learners.py
- adaptive/utils.py
- docs/environment.yml
- docs/source/_static/custom.css
- docs/source/conf.py
- docs/source/tutorial/tutorial.Learner1D.md
- example-notebook.ipynb
This code in this PR allows exporting a learner to a `pandas.DataFrame`. This will be useful when running many learners (e.g, in a `BalancingLearner`) and then being able to just concatenate the `DataFrame`s to get the combined result.
Currently saving the learner creates a `pickle` file and while this is fine for immediate use, for long term storage this is a bad practice.
I chose to use `pandas` over `xarray` because we are dealing with tabular data instead of ND dense or sparse arrays.
Ping @CameronKing
Example:
> Add getting learner's data as pandas.DataFrame; add learner.to_dataframe method

- adaptive/runner.py
- setup.py
This allows saving with e.g., pandas, like:
```python
def save_dataframe(
fname: str | list[str] | tuple[str, ...], **to_dataframe_kwargs: Any
) -> Callable[[BaseLearner], None]:
def save(learner):
df = learner.to_dataframe(**to_dataframe_kwargs)
fname_df = fname_to_dataframe(fname)
df.to_parquet(fname_df)
return save
save_task = runner.start_periodic_saving(interval=5, method=save_dataframe("test.parquet"))
```
> Allow to periodically save with any function

- CHANGELOG.md
> Release 0.14

- adaptive/learner/average_learner.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/base_learner.py
- adaptive/learner/data_saver.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/sequence_learner.py
- adaptive/learner/skopt_learner.py
- adaptive/tests/test_learners.py
Add a method that returns a new instance of the `Learner` but without any data.
This is useful for testing and very useful when sending `Learner`s over the network where its data is stored separately, e.g., in https://github.com/basnijholt/adaptive-scheduler.
> Add Learner.new() method that returns an empty copy of the learner

- adaptive/learner/learner1D.py
- adaptive/types.py
- setup.py
> Use typing.TypeAlias

- adaptive/learner/sequence_learner.py
> Typehint SequenceLearner

- adaptive/tests/test_average_learner1d.py
- adaptive/tests/test_learners.py
- setup.py
This ensures that the minimal dependencies test runs correctly.
Right now pandas is always installed.
> Optionally run tests with pandas

- adaptive/learner/integrator_coeffs.py
- adaptive/learner/integrator_learner.py
- adaptive/tests/algorithm_4.py
> Type hint IntegratorLearner

- adaptive/learner/balancing_learner.py
> Add type-hints to BalancingLearner

- adaptive/learner/average_learner.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/learner1D.py
- adaptive/learner/sequence_learner.py
- adaptive/types.py
> Use numbers module from stdlib as type

- adaptive/learner/learner2D.py
- adaptive/tests/test_pickling.py
- adaptive/tests/test_runner.py
> Add type-hints to Learner2D

- adaptive/learner/sequence_learner.py
This change is relevant when a SequenceLearner is used with an object that provides the Sequence interface, but lazily evaluates its elements.
> Avoid uncecessary iteration in SequenceLearner

- .github/workflows/nox.yml
- .github/workflows/pre-commit.yml
- README.md
- RELEASE.md
- azure-pipelines.yml
Updates references from `master` to `main`.
Fixes #383.
Tagging @loganbvh
> Rename master -> main

- docs/environment.yml
- docs/source/tutorial/tutorial.advanced-topics.md
> Add docs section about executing coroutines 

- adaptive/runner.py
- adaptive/utils.py
> Add type-hints to Runner

- adaptive/runner.py
This was accidentally broken in #370.
> Use default executor when Runner(..., executor=None)

- pyproject.toml
- setup.py
> Move to pyproject.toml based install

- .pre-commit-config.yaml
- adaptive/_version.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/integrator_coeffs.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/skopt_learner.py
- adaptive/notebook_integration.py
- adaptive/runner.py
- adaptive/tests/algorithm_4.py
- adaptive/tests/test_average_learner1d.py
- adaptive/tests/test_balancing_learner.py
- adaptive/tests/test_cquad.py
- adaptive/tests/test_learner1d.py
- adaptive/tests/test_learners.py
- adaptive/tests/test_pickling.py
- adaptive/utils.py
- pyproject.toml
> Replace isort, flake8, and pyupgrade by ruff

- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/skopt_learner.py
- docs/source/algorithms_and_examples.md
- docs/source/tutorial/tutorial.LearnerND.md
- docs/source/tutorial/tutorial.advanced-topics.md
- setup.cfg
WARNING:param.main: Calling the .opts method with options broken down by options group (i.e. separate plot, style and norm groups) is deprecated. Use the .options method converting to the simplified format instead or use hv.opts.apply_groups for backward compatibility.
> Fix HoloViews opts deprecation warnings

- docs/environment.yml
- docs/logo.py
- docs/source/conf.py
The option `nb_execution_fail_on_error` does not exist.
> Use nb_execution_raise_on_error Sphinx myst-nb option

- .pre-commit-config.yaml
- docs/source/algorithms_and_examples.md
- docs/source/logo.md
- docs/source/tutorial/tutorial.BalancingLearner.md
- docs/source/tutorial/tutorial.DataSaver.md
- docs/source/tutorial/tutorial.IntegratorLearner.md
- docs/source/tutorial/tutorial.Learner1D.md
- docs/source/tutorial/tutorial.Learner2D.md
- docs/source/tutorial/tutorial.LearnerND.md
- docs/source/tutorial/tutorial.advanced-topics.md
- docs/source/tutorial/tutorial.custom_loss.md
- example-notebook.ipynb
- readthedocs.yml
This is now possible after https://github.com/nbQA-dev/nbQA/pull/745 which solved this issue (https://github.com/nbQA-dev/nbQA/issues/668) I opened a year ago.
> Add nbQA for notebook and docs linting

- adaptive/tests/test_learner1d.py
- docs/environment.yml
- docs/source/logo.md
> Avoid asyncio.coroutine error in Readthedocs.org builds

- adaptive/learner/sequence_learner.py
- docs/source/conf.py
I noticed this when implementing tests in Adaptive Scheduler https://github.com/basnijholt/adaptive-scheduler/pull/122.
> Cache the loss of a SequenceLearner

- .github/workflows/coverage.yml
The `codecov` package has been removed from PyPI (https://about.codecov.io/blog/message-regarding-the-pypi-package/).
> Use codecov/codecov-action instead of removed codecov package

- adaptive/learner/average_learner.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/base_learner.py
- adaptive/learner/data_saver.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/sequence_learner.py
- adaptive/utils.py
This metaclass is messing with the doc-string and function signature in notebooks making it less useful than the benefit it brings.
> Remove _RequireAttrsABCMeta metaclass and replace with simple check

- .github/workflows/nox.yml
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/base_learner.py
- adaptive/learner/integrator_coeffs.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
- adaptive/learner/sequence_learner.py
- adaptive/runner.py
- adaptive/utils.py
- benchmarks/asv.conf.json
- noxfile.py
- pyproject.toml
This PR updates the minimum required Python version to 3.9, following the recommendations of [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). NEP 29 provides a formalized deprecation policy for supported Python versions in the scientific Python ecosystem, which can help us maintain compatibility and reduce maintenance overhead.
The proposed changes include:
Before proceeding with these changes, we'd like to gather input from the community (@jbweston and @akhmerov):
1.  Is there any reason to delay this update or maintain support for older Python versions?
2.  Are there any potential conflicts or compatibility issues that could arise from updating the minimum Python version?
Please provide your feedback and let us know if you have any concerns or suggestions related to …
> Update Python version requirement to 3.9 in accordance with NEP 29

- adaptive/learner/sequence_learner.py
- adaptive/tests/test_sequence_learner.py
> Allow storing the full sequence in SequenceLearner.to_dataframe

- adaptive/utils.py
- docs/source/tutorial/tutorial.advanced-topics.md
- docs/source/tutorial/tutorial.parallelism.md
@juandaanieel, I was reading the great tutorial piece you wrote in https://github.com/python-adaptive/adaptive/pull/364 and realized we might be able to simplify the code by introducing a decorator.
Please take a look at let me know whether this would work for you or not.
> Add adaptive.utils.daskify

- adaptive/learner/learner2D.py
- adaptive/tests/test_learners.py
> Add Learner2D loss function 'thresholded_loss_factory'

- adaptive/runner.py
- docs/source/tutorial/tutorial.IntegratorLearner.md
This PR modifies the behavior of periodic saving to fire immediately after the runner completes.
Previously the periodic saving would wait 'interval' seconds before firing the final save event.
Fixes #439 .
> Ensure periodic saving fires immediately after runner task is finished

- adaptive/runner.py
- adaptive/tests/test_runner.py
- docs/source/tutorial/tutorial.parallelism.md
I have answered this question so often that I think it warrents a new method.
> Add `AsyncRunner.block_until_done`

- adaptive/runner.py
Use like:
`python live-info-example.py`
```python
import asyncio
import random
offset = random.uniform(-0.5, 0.5)
def peak(x, offset=offset, wait=True):
from random import random
from time import sleep
a = 0.01
if wait:
sleep(random())
return x + a**2 / (a**2 + (x - offset) ** 2)
learner = adaptive.Learner1D(peak, bounds=(-1, 1))
runner = adaptive.Runner(learner, loss_goal=0.01)
async def run(runner, fname: str):
runner.live_info_terminal(overwrite_previous=True)
await runner.task
runner.learner.save(fname)
runner.ioloop.run_until_complete(run(runner, "learner.pkl"))
```
Fixes #436
> Add `live_info_terminal`, closes #436

- .pre-commit-config.yaml
- adaptive/learner/average_learner1D.py
- adaptive/runner.py
- adaptive/tests/algorithm_4.py
- pyproject.toml
Use Ruff instead of black, to converge to a single tool.
> Use ruff-format instead of black

- CHANGELOG.md
> Update CHANGELOG.md for v1.2.0

- adaptive/notebook_integration.py
This has been the default for years and seems to no longer work
> Remove async activation magic in notebook_integration.py

- adaptive/learner/learner2D.py
Currently, I see:
```
~/Work/pipefunc/.venv/lib/python3.13/site-packages/adaptive/learner/learner2D.py:52: DeprecationWarning: `scipy.interpolate.interpnd.estimate_gradients_2d_global` is deprecated along with the `scipy.interpolate.interpnd` namespace. `scipy.interpolate.interpnd.estimate_gradients_2d_global` will be removed in SciPy 1.16.0, and the `scipy.interpolate.interpnd` namespace will be removed in SciPy 2.0.0.
gradients = interpolate.interpnd.estimate_gradients_2d_global(
```
Unfortunately, `estimate_gradients_2d_global` is not exposed anywhere in SciPy. Its only use is via `CloughTocher2DInterpolator.grad`, so we use that.
> Prevent SciPy deprecation warning for `estimate_gradients_2d_global`

- .github/workflows/nox.yml
- adaptive/learner/average_learner.py
- adaptive/learner/average_learner1D.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/base_learner.py
- adaptive/learner/data_saver.py
- adaptive/learner/integrator_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/learner2D.py
- adaptive/learner/sequence_learner.py
- adaptive/runner.py
- adaptive/tests/algorithm_4.py
- adaptive/tests/test_average_learner1d.py
- adaptive/tests/test_notebook_integration.py
- adaptive/types.py
- adaptive/utils.py
- docs/environment.yml
- docs/source/algorithms_and_examples.md
- docs/source/tutorial/tutorial.LearnerND.md
- environment.yml
- noxfile.py
- pyproject.toml
According to https://scientific-python.org/specs/spec-0000/ we should even drop support for 3.10 already.
> Follow SPEC 0 and drop support for Python 3.9 and 3.10

- .github/workflows/typeguard.yml
- adaptive/_types.py
- adaptive/learner/balancing_learner.py
- adaptive/learner/learner1D.py
- adaptive/learner/sequence_learner.py
- adaptive/runner.py
- adaptive/tests/test_average_learner.py
- adaptive/tests/test_average_learner1d.py
- adaptive/tests/test_balancing_learner.py
- adaptive/tests/test_learner1d.py
- adaptive/tests/test_notebook_integration.py
Re-enables the typeguard job that I disabled 2 years ago in https://github.com/python-adaptive/adaptive/pull/415.
> Enable runtime type checking in tests with typeguard

- adaptive/learner/learner2D.py
- adaptive/learner/learnerND.py
Fixes:
```
FAILED adaptive/tests/test_learners.py::test_learner_performance_is_invariant_under_scaling[LearnerND-ring_of_fire-learner_kwargs12] - DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
```
and
```
.venv/lib/python3.13/site-packages/adaptive/learner/learner2D.py:313: in choose_point_in_triangle
area = 0.5 * np.cross(b - a, c - a)
if a.shape[-1] == 2 or b.shape[-1] == 2:
>           warnings.warn(
"Arrays of 2-dimensional vectors are deprecated. Use arrays of "
"3-dimensional vectors instead. (deprecated in NumPy 2.0)",
DeprecationWarning, stacklevel=2
)
E           DeprecationWarning: Arrays of 2-dimensional …
```
> Fix 2 NumPy deprecation warnings

- README.md
- adaptive/learner/learner2D.py
- adaptive/tests/test_learners.py
I am trying to adapt `adaptive` for sequential operations with a relatively fast function. I really love the package and would like to experiment with speeding up the learners themselves. This is a minor change which does not affect the speed much, as interpolators seem to be bottleneck, but since I already implemented it, I figured I'd share it :)
I also noticed the tutorial link in README is broken, so I included it here as it is a tiny change, but can remove it if you'd like.
> Remove for loops in deviations function body
