adaptive/learner/balancing_learner.py

@jbweston this should go into stable, right?

fix _get_data for the BalancingLearner

---

adaptive/notebook_integration.py

See https://github.com/pyviz/holoviews/issues/3564.
Closes  https://github.com/python-adaptive/adaptive/issues/166.

fix live_plot

---

docs/source/tutorial/tutorial.LearnerND.rst

Potentially closes https://github.com/python-adaptive/adaptive/issues/171.

LearnerND: change the required loss to 1e-3 because the loss definition changed

---

adaptive/learner/balancing_learner.py
adaptive/notebook_integration.py

Blocked by https://github.com/pyviz/holoviews/issues/3637.
Edit: not blocked anymore.

renormalize the plots value axis on every update

---

docs/environment.yml

The documentation is broken once again after a `bokeh` update...
Relevant: #169

pin everything in the docs/environment.yml file

---

adaptive/learner/learner2D.py
adaptive/tests/test_learners.py
docs/logo.py

@michaelwimmer told me this would be a useful addition. He (and many others before) struggled to get the interpolated data from the learner.
@michaelwimmer what do you think of this?

2D: add interpolated_on_grid method

---

docs/source/tutorial/tutorial.rst

I would also be fine with removing this section altogether because it will for sure get out of sync again.

update packages in tutorial's landing page

---

adaptive/runner.py
adaptive/tests/test_runner.py
docs/source/reference/adaptive.runner.extras.rst

add a time-base stopping criterion for runners

---

setup.py

We forgot to change this when merging #235.

correct short description in setup.py

---

.zenodo.json

Adds .zenodo.json file which would fix the citation on https://zenodo.org/record/2552292.

add .zenodo.json

---

.pre-commit-config.yaml
adaptive/notebook_integration.py
adaptive/tests/test_cquad.py
adaptive/tests/unit/test_triangulation.py
benchmarks/asv.conf.json
tox.ini

Update pre commit

---

README.rst

add `runner.live_plot()` in README example

---

adaptive/learner/learner1D.py
docs/source/tutorial/tutorial.custom_loss.rst

add learner1D.abs_min_log_loss

---

docs/environment.yml

Some package that was not pinned (not sure which one) had an incompatibility with Pillow.
I updated some packages to their latest versions, and it works again.

fix docs build

---

docs/source/CHANGELOG.md
docs/source/index.rst

add change log to the docs

---

.github/pull_request_template.md

add "(Code) style fix or documentation update" to .github/pull_request_template.md

add "(Code) style fix or documentation update" to .github/pull_request_template.md

---

adaptive/learner/integrator_learner.py

Here https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=294347&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00 I noticed that imports on pypy work slightly different. This fixes that problem.

write import differently for pypy

---

README.rst

Fixes #297
Make it so that new users can quickly understand *when* adaptive is particularly cool.
Based on short discussion in #297, I just got around to making it now.

Update Readme to emphasise when adaptive should be used

---

adaptive/notebook_integration.py

Behavior was changed in Python 3.7.

fix 'asyncio.Task.current_task' -> 'asyncio.current_task'

---

docs/source/algorithms_and_examples.rst

add a code example to the examples page

add a code example to the examples page

---

docs/source/tutorial/tutorial.Learner1D.rst

fix tutorial about using loky.get_reusable_executor on Windows

fix tutorial about using loky.get_reusable_executor on Windows

---

adaptive/learner/average_learner.py
adaptive/learner/average_learner1D.py
adaptive/learner/base_learner.py
adaptive/learner/learner1D.py
adaptive/runner.py

use 'from __future__ import annotations'

---

.github/workflows/nox.yml
.github/workflows/typeguard.yml
noxfile.py
setup.py

Add support for Python 3.11 and test on it

---

CHANGELOG.md

Update CHANGELOG for 0.15.0 release

---

docs/environment.yml

Bump scikit-optimize in environment.yml

---

.github/workflows/pythonpublish.yml

Use the build module

---

adaptive/learner/triangulation.py
adaptive/runner.py
docs/logo.py
docs/source/algorithms_and_examples.md
docs/source/tutorial/tutorial.AverageLearner1D.md
docs/source/tutorial/tutorial.BalancingLearner.md
docs/source/tutorial/tutorial.Learner1D.md
docs/source/tutorial/tutorial.Learner2D.md
docs/source/tutorial/tutorial.custom_loss.md
pyproject.toml

When importing adaptive most of the time is spend importing ipyparallel and distributed:

Only really import packages when needed

---

.github/workflows/typeguard.yml

Enable this again once `typeguard=4` is released and issues are fixed

Disable typeguard CI pipeline

---

.github/workflows/auto-changelog-generator.yml

Add github-changelog-generator CI workflow

---

docs/environment.yml

Bump versions to compatible packages in `docs/environment.yml`

---

.github/workflows/auto-changelog-generator.yml
.github/workflows/coverage.yml
.github/workflows/nox.yml
.github/workflows/pythonpublish.yml
.github/workflows/typeguard.yml
noxfile.py
pyproject.toml

Test Python 3.12 and fix its installation

---

README.md

Remove Azure Pipelines badge in README.md

---

readthedocs.yml

Ref: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Fix readthedocs.yml

---

CHANGELOG.md

I will release v1.4.0 after merging this PR.

Update changelog to v1.4.0
